import { Link } from 'react-router-dom'
import type { AdminCompaniesTranslations } from '../../../i18n/types'
import type { AdminCompany } from '../../../types/admin.types'
import { CompanyStatusBadge } from '../../_components/admin/CompanyStatusBadge'

type Props = { company: AdminCompany; content: AdminCompaniesTranslations['detail']; statusesLabel: AdminCompaniesTranslations['statuses'] }
const initials = (name: string) => name.split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase()
const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat().format(new Date(value)) : '—'

export function CompanyOverviewCard({ company, content, statusesLabel }: Props) {
  return <section aria-labelledby="company-overview-title" className="admin-company-panel admin-company-overview"><div className="admin-company-overview__head">{company.logoUrl || company.logo ? <img alt="" className="admin-company-overview__logo admin-company-cell__logo--image" src={company.logoUrl ?? company.logo} /> : <span aria-hidden="true" className="admin-company-overview__logo">{initials(company.name)}</span>}<div><div className="admin-company-overview__title-row"><h2 id="company-overview-title">{company.name}</h2><CompanyStatusBadge labels={statusesLabel} status={company.status} /></div><div className="admin-company-overview__links"><Link to={`/companies/${company.id}`}>{content.viewPublicPage}</Link>{company.website ? <a className="admin-company-overview__website" href={company.website} rel="noreferrer" target="_blank">{company.website}</a> : null}</div></div></div><div className="admin-company-completion"><span>{content.completionLabel}</span><strong>{company.completionPercent}%</strong><div><i style={{ width: `${Math.min(100, Math.max(0, company.completionPercent))}%` }} /></div></div><dl className="admin-company-overview__meta"><div><dt>{content.taxCodeLabel}</dt><dd>{company.taxCode}</dd></div><div><dt>{content.submittedAtLabel}</dt><dd>{formatDate(company.submittedAt)}</dd></div><div><dt>{content.contactLabel}</dt><dd>{company.contactEmail || company.contactPhone || '—'}</dd></div><div className="admin-company-overview__wide"><dt>{content.addressLabel}</dt><dd>{company.address || '—'}</dd></div></dl>{company.statusReason || company.lastVerificationRejectedReason ? <div className="admin-company-status-reason"><strong>{content.statusReasonLabel}</strong><p>{company.statusReason || company.lastVerificationRejectedReason}</p></div> : null}</section>
}
