import type { AdminAiManagementTranslations } from '../../../types'

export const adminAiManagement: AdminAiManagementTranslations = {
  routeLabel: 'Quản trị viên — Quản lý AI', pageTitle: 'Quản lý AI', sidebarLabel: 'Quản lý AI',
  pageSubtitle: 'Quản lý model và giám sát hoạt động phân tích CV trên toàn hệ thống.',
  header: { title: 'Trung tâm vận hành AI', refresh: 'Làm mới dữ liệu', refreshing: 'Đang làm mới…', healthy: 'Đang hoạt động', degraded: 'Gián đoạn', unknown: 'Chưa xác định' },
  tabs: { overview: 'Tổng quan', config: 'Cấu hình', logs: 'Nhật ký' },
  notes: { newRequests: 'Thay đổi provider/model chỉ áp dụng cho các yêu cầu phân tích CV mới.', apiKeys: 'API key được cấu hình trong môi trường backend và không hiển thị tại đây.', estimatedCost: 'Chi phí được ước tính theo bảng giá cấu hình và có thể khác hóa đơn thực tế.' },
  config: { title: 'Cấu hình vận hành', description: 'Chọn provider đang hoạt động và model được phép sử dụng cho CV parsing.', provider: 'Provider đang hoạt động', gemini: 'Gemini', openAi: 'OpenAI-compatible', geminiModel: 'Model Gemini', openAiModel: 'Model OpenAI-compatible', save: 'Lưu thay đổi', saving: 'Đang lưu…', updatedAt: 'Cập nhật lúc', updatedBy: 'Người cập nhật', neverUpdated: 'Chưa có lần cập nhật bởi quản trị viên.', loadErrorTitle: 'Không tải được cấu hình AI', loadErrorDescription: 'Form đã bị khóa để tránh lưu cấu hình không đầy đủ.', retry: 'Thử lại', success: 'Đã cập nhật cấu hình AI.', error: 'Không thể cập nhật cấu hình AI.', undo: 'Hoàn tác', activeProvider: 'Provider đang chọn', selectedModel: 'Model sẽ sử dụng' },
  summary: { title: 'Tổng quan sử dụng', description: 'Số liệu tổng hợp theo provider và model trong 30 ngày gần nhất.', totalRequests: 'Tổng yêu cầu', succeededRequests: 'Thành công', failedRequests: 'Thất bại', totalTokens: 'Tổng token', estimatedCost: 'Chi phí ước tính', noPricing: 'Chưa cấu hình giá', empty: 'Chưa có dữ liệu sử dụng AI trong 30 ngày gần nhất.', errorTitle: 'Không tải được thống kê AI', errorDescription: 'Cấu hình vận hành vẫn có thể sử dụng bình thường.', retry: 'Thử lại', successRate: 'Tỷ lệ thành công', providerBreakdown: 'Chi tiết theo provider và model', columns: { provider: 'Provider', model: 'Model', requests: 'Request', success: 'Thành công', failed: 'Thất bại', failureRate: 'Tỷ lệ lỗi', inputTokens: 'Input token', outputTokens: 'Output token', totalTokens: 'Tổng token', cost: 'Chi phí' } },
  logs: { title: 'Nhật ký sử dụng', description: 'Theo dõi từng yêu cầu AI phục vụ kiểm tra và xử lý sự cố.', count: '{{count}} bản ghi', provider: 'Provider', model: 'Model', status: 'Trạng thái', dateFrom: 'Từ ngày', dateTo: 'Đến ngày', candidateCvId: 'Candidate CV ID', allProviders: 'Tất cả provider', allModels: 'Tất cả model', allStatuses: 'Tất cả trạng thái', apply: 'Áp dụng', clear: 'Xóa lọc', loading: 'Đang tải nhật ký…', errorTitle: 'Không tải được nhật ký AI', errorDescription: 'Kiểm tra lại bộ lọc hoặc thử lại sau.', retry: 'Thử lại', emptyTitle: 'Không có nhật ký phù hợp', emptyDescription: 'Thử thay đổi hoặc xóa bớt bộ lọc.', copied: 'Đã sao chép ID.', copy: 'Sao chép', noValue: '—', succeeded: 'Thành công', failed: 'Thất bại', noPricing: 'Chưa có giá', columns: { request: 'Request / CV', providerModel: 'Provider / Model', status: 'Trạng thái', tokens: 'Token', latency: 'Độ trễ', cost: 'Chi phí', createdAt: 'Thời gian', error: 'Lỗi' } },
  pagination: { prev: 'Trang trước', next: 'Trang sau', pageOf: 'Trang {{current}} / {{total}}' },
}
