import type { AdminJobsTranslations } from '../../../types'

export const adminJobs: AdminJobsTranslations = {
  routeLabel: 'Quản trị viên — Tin tuyển dụng',
  pageTitle: 'Kiểm duyệt tin tuyển dụng',
  pageSubtitle: 'Theo dõi nội dung, mức độ rủi ro và xử lý các hàng đợi kiểm duyệt.',
  tabs: { all: 'Tất cả tin', review: 'Tin chờ duyệt', revisions: 'Bản chỉnh sửa' },
  stats: { total: 'Tổng tin', review: 'Chờ kiểm duyệt', published: 'Đang đăng', revisions: 'Bản sửa chờ duyệt' },
  filters: { searchLabel: 'Tìm kiếm', searchPlaceholder: 'Tiêu đề, công ty, địa điểm hoặc kỹ năng', statusLabel: 'Trạng thái', statusAll: 'Tất cả trạng thái', riskLabel: 'Mức rủi ro', riskAll: 'Tất cả mức độ', companyLabel: 'Công ty', companyAll: 'Tất cả công ty', sortLabel: 'Sắp xếp', clear: 'Xóa lọc' },
  columns: { job: 'Tin tuyển dụng', company: 'Công ty', status: 'Trạng thái', risk: 'Rủi ro', applications: 'Ứng tuyển', updated: 'Cập nhật', actions: 'Hành động' },
  statuses: { DRAFT: 'Bản nháp', PENDING_REVIEW: 'Chờ duyệt', NEEDS_REVIEW: 'Cần xem xét', SHOULD_REJECT: 'Đề xuất từ chối', PUBLISHED: 'Đã đăng', UNPUBLISHED: 'Đã ẩn', REJECTED: 'Đã từ chối', CLOSED: 'Đã đóng', EXPIRED: 'Hết hạn', APPROVED: 'Đã duyệt', CANCELLED: 'Đã hủy' },
  risks: { LOW: 'Thấp', MEDIUM: 'Trung bình', HIGH: 'Cao', CRITICAL: 'Nghiêm trọng', NONE: 'Chưa đánh giá' },
  sorts: { latest: 'Mới nhất', oldest: 'Cũ nhất', risk: 'Rủi ro cao nhất', applications: 'Nhiều ứng tuyển nhất' },
  detail: { title: 'Chi tiết kiểm duyệt', description: 'Mô tả công việc', requirements: 'Yêu cầu', benefits: 'Quyền lợi', skills: 'Kỹ năng', moderation: 'Phân tích kiểm duyệt', reasons: 'Lý do cảnh báo', rules: 'Quy tắc khớp', reasonLabels: { 'Job description is too short': 'Mô tả công việc quá ngắn', 'Job requirements are missing or too vague': 'Yêu cầu tuyển dụng bị thiếu hoặc chưa rõ ràng' }, ruleLabels: { LOW_DESCRIPTION_LENGTH: 'Mô tả công việc quá ngắn', MISSING_OR_WEAK_REQUIREMENTS: 'Yêu cầu tuyển dụng bị thiếu hoặc chưa rõ ràng', CLIENT_SITE_SCOPE: 'Tin tuyển dụng chỉ áp dụng cho ứng viên tại khu vực của khách hàng', MULTI_LEVEL_PATTERN: 'Nội dung có dấu hiệu mô hình đa cấp', MISSING_COMPENSATION: 'Thiếu thông tin lương hoặc đãi ngộ' }, changeSummary: 'Tóm tắt thay đổi', noData: 'Chưa có dữ liệu', close: 'Đóng' },
  actions: { view: 'Xem chi tiết', approve: 'Duyệt', reject: 'Từ chối', unpublish: 'Gỡ đăng', republish: 'Đăng lại', close: 'Đóng tin', cancel: 'Hủy', confirmTitle: 'Xác nhận thao tác', confirmDescription: 'Bạn có chắc muốn {{action}} “{{title}}”?', reasonTitle: 'Nhập lý do xử lý', reasonDescription: 'Vui lòng nêu rõ lý do {{action}} “{{title}}”.', reasonLabel: 'Lý do', reasonPlaceholder: 'Nhập lý do để nhà tuyển dụng và quản trị viên có thể đối chiếu...', reasonRequired: 'Lý do không được để trống.' },
  feedback: { loading: 'Đang tải dữ liệu tin tuyển dụng', errorTitle: 'Không tải được tin tuyển dụng', errorDescription: 'Không thể lấy dữ liệu quản trị tin tuyển dụng.', retry: 'Thử lại', emptyTitle: 'Không có tin phù hợp', emptyDescription: 'Hãy thay đổi từ khóa hoặc bộ lọc để mở rộng kết quả.', countLabel: '{{count}} tin tuyển dụng', actionSuccess: 'Cập nhật tin tuyển dụng thành công.', actionError: 'Không thể thực hiện thao tác.' },
  pagination: { prev: 'Trang trước', next: 'Trang sau', pageOf: 'Trang {{current}} / {{total}}' },
}

Object.assign(adminJobs.detail.ruleLabels, {
  RISK_KEYWORD_EASY_MONEY: 'Hứa hẹn việc nhẹ lương cao', RISK_KEYWORD_UNREALISTIC_PROMISE: 'Hứa hẹn thu nhập cao không cần kinh nghiệm', RISK_KEYWORD_UNREALISTIC_REMOTE_INCOME: 'Cam kết thu nhập làm việc từ xa không thực tế', RISK_KEYWORD_INCOME_GUARANTEE: 'Cam kết thu nhập thiếu căn cứ', RISK_KEYWORD_UNLIMITED_INCOME: 'Nêu thu nhập không giới hạn', RISK_KEYWORD_MASS_HIRING: 'Tuyển gấp số lượng lớn', RISK_KEYWORD_NO_INTERVIEW: 'Không yêu cầu phỏng vấn', RISK_KEYWORD_INSTANT_HIRING: 'Cam kết nhận việc ngay trong ngày', RISK_KEYWORD_UPFRONT_FEE: 'Yêu cầu đóng phí trước', RISK_KEYWORD_APPLICATION_FEE: 'Thu phí hồ sơ', RISK_KEYWORD_TRAINING_FEE: 'Thu phí đào tạo', RISK_KEYWORD_UNIFORM_FEE: 'Thu phí đồng phục', RISK_KEYWORD_ADVANCE_TRANSFER: 'Yêu cầu chuyển khoản trước', RISK_KEYWORD_DEPOSIT: 'Yêu cầu đặt cọc', RISK_KEYWORD_TOP_UP: 'Yêu cầu nạp tiền', RISK_KEYWORD_BUY_ACCOUNT: 'Yêu cầu mua tài khoản', RISK_KEYWORD_TELEGRAM_CONTACT: 'Yêu cầu liên hệ qua Telegram', RISK_KEYWORD_PRIVATE_ZALO: 'Yêu cầu liên hệ Zalo riêng', RISK_KEYWORD_PRIVATE_INBOX: 'Yêu cầu nhắn tin riêng', RISK_KEYWORD_OFF_PLATFORM_CONTACT: 'Yêu cầu liên hệ ngoài nền tảng', RISK_KEYWORD_EXTERNAL_LINK: 'Yêu cầu truy cập liên kết ngoài', RISK_SENSITIVE_DOCUMENT_REQUEST: 'Yêu cầu giấy tờ tùy thân nhạy cảm', RISK_SENSITIVE_HOUSEHOLD_DOCUMENT: 'Yêu cầu sổ hộ khẩu', RISK_BANK_CARD_REQUEST: 'Yêu cầu ảnh thẻ ngân hàng', RISK_BANK_INFO_REQUEST: 'Yêu cầu thông tin tài khoản ngân hàng', MISSING_LOCATION: 'Thiếu hoặc không rõ địa điểm làm việc', ABNORMAL_SALARY_BY_EXPERIENCE_LEVEL: 'Mức lương bất thường so với kinh nghiệm yêu cầu', RISK_SHORTENED_URL: 'Có liên kết rút gọn', TOO_MANY_EXTERNAL_LINKS: 'Có quá nhiều liên kết ngoài', RISK_EXTERNAL_FORM: 'Có liên kết đến biểu mẫu bên ngoài', TITLE_ALL_CAPS: 'Tiêu đề viết toàn bộ chữ in hoa', EXCESSIVE_SYMBOLS_IN_TITLE: 'Tiêu đề chứa quá nhiều ký tự đặc biệt', KEYWORD_STUFFING: 'Nội dung lặp lại từ khóa quá nhiều', REMOTE_JOB_WITH_UPFRONT_PAYMENT: 'Việc từ xa yêu cầu thanh toán trước', INTERNSHIP_UNREALISTIC_NO_EXPERIENCE_SALARY: 'Thực tập hứa hẹn lương cao không cần kinh nghiệm', LOW_COMPANY_TRUST_LEVEL: 'Công ty có mức độ tin cậy thấp',
})

Object.assign(adminJobs.detail.ruleLabels, { NEW_JOB_STANDARD_REVIEW: 'Tin mới cần kiểm duyệt theo tiêu chuẩn' })
Object.assign(adminJobs.detail.ruleLabels, { AMBIGUOUS_WORKING_HOURS: 'Thời gian làm việc chưa rõ ràng' })
Object.assign(adminJobs.detail.ruleLabels, { SENSITIVE_DATA_SCOPE: 'Phạm vi yêu cầu dữ liệu nhạy cảm chưa rõ ràng', AMBIGUOUS_FINANCIAL_BENEFIT: 'Quyền lợi tài chính chưa rõ ràng' })
Object.assign(adminJobs.detail.reasonLabels, { 'New job from low trust company': 'Tin mới từ doanh nghiệp có độ tin cậy thấp' })
