import type { AdminSettingsTranslations } from '../../../types'

export const adminSettings: AdminSettingsTranslations = {
  routeLabel: 'Admin — Settings', pageTitle: 'Admin settings', pageSubtitle: 'Manage your profile, security, and display preferences.',
  summary: { accountId: 'Account ID', email: 'Email', role: 'Role', adminRole: 'Administrator', fallbackName: 'NexHire Administrator', changeAvatar: 'Change photo', saveAvatar: 'Save photo', cancelAvatar: 'Cancel', removeAvatar: 'Remove photo', avatarHint: 'JPG, PNG or WEBP, up to 5 MB.', invalidAvatar: 'Use a JPG, PNG or WEBP image no larger than 5 MB.', avatarError: 'Unable to update the profile photo.' },
  profile: { title: 'Personal information', description: 'This information identifies your account in the admin workspace.', fullName: 'Full name', fullNamePlaceholder: 'Enter your full name', phone: 'Phone number', phonePlaceholder: 'Enter your phone number', email: 'Sign-in email', emailHint: 'Email cannot be changed here.', role: 'Role', save: 'Save changes', saving: 'Saving...', reset: 'Discard changes', saveSuccess: 'Account information updated.', saveError: 'Could not update account information.', validation: { fullNameRequired: 'Enter your full name.', fullNameMin: 'Full name must contain at least 2 characters.', fullNameMax: 'Full name cannot exceed 255 characters.', phoneInvalid: 'Enter a valid phone number.', phoneMax: 'Phone number cannot exceed 30 characters.' } },
  password: { title: 'Change password', description: 'Use a strong password that differs from your current password.', current: 'Current password', next: 'New password', confirm: 'Confirm new password', show: 'Show password', hide: 'Hide password', submit: 'Update password', submitting: 'Updating...', success: 'Password changed successfully.', error: 'Could not change password.', rulesTitle: 'A strong password should include:', lengthRule: '8 to 128 characters', caseRule: 'Uppercase and lowercase letters', numberRule: 'At least one number', symbolRule: 'At least one special character', validation: { currentRequired: 'Enter your current password.', nextRequired: 'Enter a new password.', confirmRequired: 'Confirm your new password.', length: 'Password must contain 8 to 128 characters.', mismatch: 'Passwords do not match.', reuse: 'The new password must differ from the current password.' }, apiErrors: { invalidCredentials: 'The current password is incorrect.', passwordReuse: 'The new password cannot reuse the current password.', credentialMissing: 'Password credentials were not found for this account.' } },
  preferences: { title: 'Preferences and session', description: 'Adjust the interface language or end the current admin session.', language: 'Display language', languageHint: 'The header dropdown only changes this device temporarily. Save here to sync it to your account.', languageReset: 'Reset', languageSave: 'Save language', languageSaveError: 'Language could not be saved.', languageSaveSuccess: 'Display language has been saved.', languageSaving: 'Saving...', sessionTitle: 'Signed-in session', sessionDescription: 'Sign out securely from this device.', logout: 'Sign out' },
  logout: { title: 'Confirm sign out', description: 'You will need to sign in again to access the admin workspace.', confirm: 'Sign out', cancel: 'Stay signed in' },
  feedback: { loading: 'Loading account information', errorTitle: 'Unable to load settings', errorDescription: 'Admin account information could not be retrieved.', retry: 'Try again' },
}
