import type { AdminJobsTranslations } from '../../../types'

export const adminJobs: AdminJobsTranslations = {
  routeLabel: 'Admin — Jobs', pageTitle: 'Job moderation', pageSubtitle: 'Review content, risk signals, and moderation queues.',
  tabs: { all: 'All jobs', review: 'Review queue', revisions: 'Revision queue' },
  stats: { total: 'Total jobs', review: 'Waiting for review', published: 'Published', revisions: 'Revisions waiting' },
  filters: { searchLabel: 'Search', searchPlaceholder: 'Title, company, location, or skill', statusLabel: 'Status', statusAll: 'All statuses', riskLabel: 'Risk level', riskAll: 'All risk levels', companyLabel: 'Company', companyAll: 'All companies', sortLabel: 'Sort', clear: 'Clear filters' },
  columns: { job: 'Job', company: 'Company', status: 'Status', risk: 'Risk', applications: 'Applications', updated: 'Updated', actions: 'Actions' },
  statuses: { DRAFT: 'Draft', PENDING_REVIEW: 'Pending review', NEEDS_REVIEW: 'Needs review', SHOULD_REJECT: 'Suggested rejection', PUBLISHED: 'Published', UNPUBLISHED: 'Unpublished', REJECTED: 'Rejected', CLOSED: 'Closed', EXPIRED: 'Expired', APPROVED: 'Approved', CANCELLED: 'Cancelled' },
  risks: { LOW: 'Low', MEDIUM: 'Medium', HIGH: 'High', CRITICAL: 'Critical', NONE: 'Not assessed' },
  sorts: { latest: 'Newest', oldest: 'Oldest', risk: 'Highest risk', applications: 'Most applications' },
  detail: { title: 'Moderation details', description: 'Job description', requirements: 'Requirements', benefits: 'Benefits', skills: 'Skills', moderation: 'Moderation analysis', reasons: 'Warning reasons', rules: 'Matched rules', reasonLabels: {}, ruleLabels: { LOW_DESCRIPTION_LENGTH: 'Job description is too short', MISSING_OR_WEAK_REQUIREMENTS: 'Job requirements are missing or too vague', CLIENT_SITE_SCOPE: 'Client-site scope', MULTI_LEVEL_PATTERN: 'Potential multi-level marketing pattern', MISSING_COMPENSATION: 'Compensation information is missing' }, changeSummary: 'Change summary', noData: 'No data', close: 'Close' },
  actions: { view: 'View details', approve: 'Approve', reject: 'Reject', unpublish: 'Unpublish', republish: 'Republish', close: 'Close job', cancel: 'Cancel', confirmTitle: 'Confirm action', confirmDescription: 'Are you sure you want to {{action}} “{{title}}”?', reasonTitle: 'Enter an action reason', reasonDescription: 'Explain why you want to {{action}} “{{title}}”.', reasonLabel: 'Reason', reasonPlaceholder: 'Enter a clear reason for the recruiter and audit history...', reasonRequired: 'Reason is required.' },
  feedback: { loading: 'Loading admin jobs', errorTitle: 'Unable to load jobs', errorDescription: 'Admin job data could not be loaded.', retry: 'Retry', emptyTitle: 'No matching jobs', emptyDescription: 'Change the keyword or filters to broaden the results.', countLabel: '{{count}} jobs', actionSuccess: 'Job updated successfully.', actionError: 'The action could not be completed.' },
  pagination: { prev: 'Previous page', next: 'Next page', pageOf: 'Page {{current}} of {{total}}' },
}

Object.assign(adminJobs.detail.ruleLabels, {
  RISK_KEYWORD_EASY_MONEY: 'Easy-money promise', RISK_KEYWORD_UNREALISTIC_PROMISE: 'Unrealistic no-experience income promise', RISK_KEYWORD_UNREALISTIC_REMOTE_INCOME: 'Unrealistic remote-income promise', RISK_KEYWORD_INCOME_GUARANTEE: 'Unfounded income guarantee', RISK_KEYWORD_UNLIMITED_INCOME: 'Unlimited-income language', RISK_KEYWORD_MASS_HIRING: 'Mass-hiring urgency', RISK_KEYWORD_NO_INTERVIEW: 'No interview required', RISK_KEYWORD_INSTANT_HIRING: 'Same-day hiring promise', RISK_KEYWORD_UPFRONT_FEE: 'Upfront fee request', RISK_KEYWORD_APPLICATION_FEE: 'Application fee', RISK_KEYWORD_TRAINING_FEE: 'Training fee', RISK_KEYWORD_UNIFORM_FEE: 'Uniform fee', RISK_KEYWORD_ADVANCE_TRANSFER: 'Advance-transfer request', RISK_KEYWORD_DEPOSIT: 'Deposit request', RISK_KEYWORD_TOP_UP: 'Top-up request', RISK_KEYWORD_BUY_ACCOUNT: 'Account-purchase request', RISK_KEYWORD_TELEGRAM_CONTACT: 'Telegram contact request', RISK_KEYWORD_PRIVATE_ZALO: 'Private Zalo contact request', RISK_KEYWORD_PRIVATE_INBOX: 'Private inbox contact request', RISK_KEYWORD_OFF_PLATFORM_CONTACT: 'Off-platform contact request', RISK_KEYWORD_EXTERNAL_LINK: 'External-link request', RISK_SENSITIVE_DOCUMENT_REQUEST: 'Sensitive identity-document request', RISK_SENSITIVE_HOUSEHOLD_DOCUMENT: 'Household-registration document request', RISK_BANK_CARD_REQUEST: 'Bank-card image request', RISK_BANK_INFO_REQUEST: 'Bank-account information request', MISSING_LOCATION: 'Location is missing or unclear', ABNORMAL_SALARY_BY_EXPERIENCE_LEVEL: 'Salary is unusually high for the required experience', RISK_SHORTENED_URL: 'Shortened URL', TOO_MANY_EXTERNAL_LINKS: 'Too many external links', RISK_EXTERNAL_FORM: 'External form link', TITLE_ALL_CAPS: 'All-caps title', EXCESSIVE_SYMBOLS_IN_TITLE: 'Too many special characters in the title', KEYWORD_STUFFING: 'Excessive repeated keywords', REMOTE_JOB_WITH_UPFRONT_PAYMENT: 'Remote job requires upfront payment', INTERNSHIP_UNREALISTIC_NO_EXPERIENCE_SALARY: 'Internship promises high pay with no experience', LOW_COMPANY_TRUST_LEVEL: 'Company has a low trust level',
})

Object.assign(adminJobs.detail.ruleLabels, { NEW_JOB_STANDARD_REVIEW: 'New job requires standard review' })
Object.assign(adminJobs.detail.ruleLabels, { AMBIGUOUS_WORKING_HOURS: 'Working hours are unclear' })
Object.assign(adminJobs.detail.ruleLabels, { SENSITIVE_DATA_SCOPE: 'Sensitive-data scope is unclear', AMBIGUOUS_FINANCIAL_BENEFIT: 'Financial benefits are unclear' })
Object.assign(adminJobs.detail.reasonLabels, { 'New job from low trust company': 'New job from a low-trust company' })
