import type { AdminAiManagementTranslations } from '../../../types'

export const adminAiManagement: AdminAiManagementTranslations = {
  routeLabel: 'Administrator — AI management', pageTitle: 'AI management', sidebarLabel: 'AI management',
  pageSubtitle: 'Manage models and monitor CV parsing activity across the platform.',
  header: { title: 'AI operations center', refresh: 'Refresh data', refreshing: 'Refreshing…', healthy: 'Operational', degraded: 'Degraded', unknown: 'Unknown' },
  tabs: { overview: 'Overview', config: 'Configuration', logs: 'Usage logs' },
  notes: { newRequests: 'Provider/model changes affect new CV parsing jobs only.', apiKeys: 'API keys are configured in the backend environment and are not visible here.', estimatedCost: 'Cost is estimated from configured model pricing and may differ from provider billing.' },
  config: { title: 'Runtime configuration', description: 'Select the active provider and allowed models for CV parsing.', provider: 'Active provider', gemini: 'Gemini', openAi: 'OpenAI-compatible', geminiModel: 'Gemini model', openAiModel: 'OpenAI-compatible model', save: 'Save changes', saving: 'Saving…', updatedAt: 'Updated at', updatedBy: 'Updated by', neverUpdated: 'No administrator update has been recorded.', loadErrorTitle: 'AI configuration unavailable', loadErrorDescription: 'The form is disabled to prevent an incomplete update.', retry: 'Retry', success: 'AI configuration updated.', error: 'Could not update AI configuration.', undo: 'Undo', activeProvider: 'Selected provider', selectedModel: 'Model to use' },
  summary: { title: 'Usage overview', description: 'Provider/model totals for the last 30 days.', totalRequests: 'Total requests', succeededRequests: 'Succeeded', failedRequests: 'Failed', totalTokens: 'Total tokens', estimatedCost: 'Estimated cost', noPricing: 'Pricing unavailable', empty: 'No AI usage has been recorded in the last 30 days.', errorTitle: 'AI usage summary unavailable', errorDescription: 'Runtime configuration remains available.', retry: 'Retry', successRate: 'Success rate', providerBreakdown: 'Provider and model breakdown', columns: { provider: 'Provider', model: 'Model', requests: 'Requests', success: 'Success', failed: 'Failed', failureRate: 'Failure rate', inputTokens: 'Input tokens', outputTokens: 'Output tokens', totalTokens: 'Total tokens', cost: 'Cost' } },
  logs: { title: 'Usage logs', description: 'Inspect individual AI requests for auditing and troubleshooting.', count: '{{count}} records', provider: 'Provider', model: 'Model', status: 'Status', dateFrom: 'From', dateTo: 'To', candidateCvId: 'Candidate CV ID', allProviders: 'All providers', allModels: 'All models', allStatuses: 'All statuses', apply: 'Apply', clear: 'Clear', loading: 'Loading usage logs…', errorTitle: 'Usage logs unavailable', errorDescription: 'Adjust the filters or try again later.', retry: 'Retry', emptyTitle: 'No matching usage logs', emptyDescription: 'Change or clear some filters.', copied: 'ID copied.', copy: 'Copy', noValue: '—', succeeded: 'Succeeded', failed: 'Failed', noPricing: 'No pricing', columns: { request: 'Request / CV', providerModel: 'Provider / Model', status: 'Status', tokens: 'Tokens', latency: 'Latency', cost: 'Cost', createdAt: 'Created', error: 'Error' } },
  pagination: { prev: 'Previous page', next: 'Next page', pageOf: 'Page {{current}} / {{total}}' },
}
