import type {
  RecruiterApplicationItem,
  RecruiterApplicationStats,
  RecruiterApplicationStatus,
} from '../types'

export const recruiterApplicationsFixture: ReadonlyArray<RecruiterApplicationItem> = [
  {
    id: 'app-001',
    candidateEmail: 'khoa.nguyen@example.com',
    candidateHeadline: 'Senior Frontend Engineer',
    candidateLocation: 'Ha Noi',
    candidateName: 'Nguyen Minh Khoa',
    candidatePhone: '0901 234 567',
    coverLetter: 'I have led React migration projects and want to help NexHire scale recruiter-facing workflows with reliable UI patterns.',
    expectedSalary: '45-55M VND',
    experience: '6 years',
    jobId: 'frontend-engineer',
    jobTitle: 'Senior Frontend Engineer',
    portfolioUrl: 'https://portfolio.example.com/khoa',
    resumeUrl: 'https://example.com/cv/nguyen-minh-khoa.pdf',
    score: 92,
    skills: ['React', 'TypeScript', 'Vite', 'Design System'],
    status: 'new',
    submittedAt: '21/07/2026',
    submittedAtOrder: 20260721,
    timeline: [
      {
        id: 'app-001-submit',
        date: '21/07/2026',
        description: 'Candidate submitted CV and cover letter.',
        label: 'Application received',
      },
    ],
    updatedAt: '21/07/2026',
  },
  {
    id: 'app-002',
    candidateEmail: 'huong.tran@example.com',
    candidateHeadline: 'Backend Engineer',
    candidateLocation: 'Da Nang',
    candidateName: 'Tran Thi Huong',
    candidatePhone: '0912 345 678',
    coverLetter: 'My recent work focuses on API reliability, queue processing, and clean service boundaries for fast-growing products.',
    expectedSalary: '38-48M VND',
    experience: '5 years',
    jobId: 'backend-engineer',
    jobTitle: 'Backend Engineer',
    resumeUrl: 'https://example.com/cv/tran-thi-huong.pdf',
    score: 86,
    skills: ['Node.js', 'PostgreSQL', 'AWS', 'REST API'],
    status: 'interview',
    submittedAt: '20/07/2026',
    submittedAtOrder: 20260720,
    timeline: [
      {
        id: 'app-002-submit',
        date: '20/07/2026',
        description: 'Candidate submitted application.',
        label: 'Application received',
      },
      {
        id: 'app-002-screen',
        date: '21/07/2026',
        description: 'Recruiter moved candidate to interview stage.',
        label: 'Interview scheduled',
      },
    ],
    updatedAt: '21/07/2026',
  },
  {
    id: 'app-003',
    candidateEmail: 'bao.le@example.com',
    candidateHeadline: 'Product Designer',
    candidateLocation: 'Ho Chi Minh City',
    candidateName: 'Le Quoc Bao',
    candidatePhone: '0933 224 466',
    coverLetter: 'I bring product discovery, UX research, and high-fidelity UI skills for hiring products with complex workflows.',
    expectedSalary: '35-45M VND',
    experience: '4 years',
    jobId: 'product-designer',
    jobTitle: 'Product Designer',
    portfolioUrl: 'https://portfolio.example.com/bao',
    resumeUrl: 'https://example.com/cv/le-quoc-bao.pdf',
    score: 78,
    skills: ['Figma', 'UX Research', 'Prototype', 'Design QA'],
    status: 'screening',
    submittedAt: '19/07/2026',
    submittedAtOrder: 20260719,
    timeline: [
      {
        id: 'app-003-submit',
        date: '19/07/2026',
        description: 'Candidate submitted portfolio and CV.',
        label: 'Application received',
      },
    ],
    updatedAt: '20/07/2026',
  },
  {
    id: 'app-004',
    candidateEmail: 'anh.pham@example.com',
    candidateHeadline: 'QA Automation Engineer',
    candidateLocation: 'Ha Noi',
    candidateName: 'Pham Hoang Anh',
    candidatePhone: '0977 118 899',
    coverLetter: 'I specialize in Playwright suites, CI stability, and clear reporting for product teams.',
    expectedSalary: '30-38M VND',
    experience: '4 years',
    jobId: 'qa-automation',
    jobTitle: 'QA Automation Engineer',
    resumeUrl: 'https://example.com/cv/pham-hoang-anh.pdf',
    score: 83,
    skills: ['Playwright', 'Cypress', 'Testing Library', 'CI'],
    status: 'new',
    submittedAt: '18/07/2026',
    submittedAtOrder: 20260718,
    timeline: [
      {
        id: 'app-004-submit',
        date: '18/07/2026',
        description: 'Candidate submitted application.',
        label: 'Application received',
      },
    ],
    updatedAt: '18/07/2026',
  },
  {
    id: 'app-005',
    candidateEmail: 'mai.do@example.com',
    candidateHeadline: 'Talent Acquisition Specialist',
    candidateLocation: 'Ho Chi Minh City',
    candidateName: 'Do Thanh Mai',
    candidatePhone: '0988 445 210',
    coverLetter: 'I have managed hiring pipelines for technology teams and improved candidate response discipline.',
    expectedSalary: '28-34M VND',
    experience: '5 years',
    jobId: 'talent-acquisition',
    jobTitle: 'Talent Acquisition Specialist',
    resumeUrl: 'https://example.com/cv/do-thanh-mai.pdf',
    score: 81,
    skills: ['Sourcing', 'Interviewing', 'ATS', 'Employer Branding'],
    status: 'offer',
    submittedAt: '17/07/2026',
    submittedAtOrder: 20260717,
    timeline: [
      {
        id: 'app-005-submit',
        date: '17/07/2026',
        description: 'Candidate submitted application.',
        label: 'Application received',
      },
      {
        id: 'app-005-offer',
        date: '21/07/2026',
        description: 'Hiring team prepared offer discussion.',
        label: 'Offer in progress',
      },
    ],
    updatedAt: '21/07/2026',
  },
  {
    id: 'app-006',
    candidateEmail: 'linh.vu@example.com',
    candidateHeadline: 'Data Analyst',
    candidateLocation: 'Ha Noi',
    candidateName: 'Vu Gia Linh',
    candidatePhone: '0904 112 233',
    coverLetter: 'I turn recruiter and product data into useful dashboards, clean metrics, and practical decision support.',
    expectedSalary: '27-35M VND',
    experience: '3 years',
    jobId: 'data-analyst',
    jobTitle: 'Data Analyst',
    resumeUrl: 'https://example.com/cv/vu-gia-linh.pdf',
    score: 75,
    skills: ['SQL', 'Power BI', 'Python', 'Product Analytics'],
    status: 'screening',
    submittedAt: '16/07/2026',
    submittedAtOrder: 20260716,
    timeline: [
      {
        id: 'app-006-submit',
        date: '16/07/2026',
        description: 'Candidate submitted application.',
        label: 'Application received',
      },
    ],
    updatedAt: '17/07/2026',
  },
  {
    id: 'app-007',
    candidateEmail: 'nam.ho@example.com',
    candidateHeadline: 'DevOps Engineer',
    candidateLocation: 'Da Nang',
    candidateName: 'Ho Duc Nam',
    candidatePhone: '0966 733 211',
    coverLetter: 'My background covers deployment pipelines, monitoring, and cost-aware cloud infrastructure.',
    expectedSalary: '42-52M VND',
    experience: '7 years',
    jobId: 'devops-engineer',
    jobTitle: 'DevOps Engineer',
    resumeUrl: 'https://example.com/cv/ho-duc-nam.pdf',
    score: 89,
    skills: ['Kubernetes', 'AWS', 'Terraform', 'Observability'],
    status: 'interview',
    submittedAt: '15/07/2026',
    submittedAtOrder: 20260715,
    timeline: [
      {
        id: 'app-007-submit',
        date: '15/07/2026',
        description: 'Candidate submitted application.',
        label: 'Application received',
      },
      {
        id: 'app-007-interview',
        date: '18/07/2026',
        description: 'Technical interview was added to the pipeline.',
        label: 'Interview scheduled',
      },
    ],
    updatedAt: '18/07/2026',
  },
  {
    id: 'app-008',
    candidateEmail: 'yen.ngo@example.com',
    candidateHeadline: 'Business Analyst',
    candidateLocation: 'Ho Chi Minh City',
    candidateName: 'Ngo My Yen',
    candidatePhone: '0944 551 882',
    coverLetter: 'I bridge business goals and engineering delivery through clear requirements and stakeholder facilitation.',
    expectedSalary: '30-40M VND',
    experience: '5 years',
    jobId: 'business-analyst',
    jobTitle: 'Business Analyst',
    resumeUrl: 'https://example.com/cv/ngo-my-yen.pdf',
    score: 72,
    skills: ['Requirements', 'Scrum', 'UAT', 'Stakeholder Management'],
    status: 'rejected',
    submittedAt: '14/07/2026',
    submittedAtOrder: 20260714,
    timeline: [
      {
        id: 'app-008-submit',
        date: '14/07/2026',
        description: 'Candidate submitted application.',
        label: 'Application received',
      },
      {
        id: 'app-008-reject',
        date: '16/07/2026',
        description: 'Recruiter closed this application after screening.',
        label: 'Application closed',
      },
    ],
    updatedAt: '16/07/2026',
  },
  {
    id: 'app-009',
    candidateEmail: 'son.bui@example.com',
    candidateHeadline: 'Mobile Engineer',
    candidateLocation: 'Ha Noi',
    candidateName: 'Bui Thanh Son',
    candidatePhone: '0909 334 455',
    coverLetter: 'I build mobile experiences with React Native and care deeply about performance on real devices.',
    expectedSalary: '36-46M VND',
    experience: '5 years',
    jobId: 'mobile-engineer',
    jobTitle: 'Mobile Engineer',
    portfolioUrl: 'https://portfolio.example.com/son',
    resumeUrl: 'https://example.com/cv/bui-thanh-son.pdf',
    score: 84,
    skills: ['React Native', 'iOS', 'Android', 'Performance'],
    status: 'hired',
    submittedAt: '13/07/2026',
    submittedAtOrder: 20260713,
    timeline: [
      {
        id: 'app-009-submit',
        date: '13/07/2026',
        description: 'Candidate submitted application.',
        label: 'Application received',
      },
      {
        id: 'app-009-hired',
        date: '20/07/2026',
        description: 'Hiring team marked candidate as hired.',
        label: 'Candidate hired',
      },
    ],
    updatedAt: '20/07/2026',
  },
  {
    id: 'app-010',
    candidateEmail: 'quynh.lam@example.com',
    candidateHeadline: 'Frontend Engineer',
    candidateLocation: 'Can Tho',
    candidateName: 'Lam Nhu Quynh',
    candidatePhone: '0922 881 774',
    coverLetter: 'I enjoy building accessible UI components and translating complex flows into simple interfaces.',
    expectedSalary: '26-34M VND',
    experience: '3 years',
    jobId: 'frontend-engineer',
    jobTitle: 'Senior Frontend Engineer',
    resumeUrl: 'https://example.com/cv/lam-nhu-quynh.pdf',
    score: 69,
    skills: ['React', 'CSS', 'Accessibility', 'Testing'],
    status: 'new',
    submittedAt: '12/07/2026',
    submittedAtOrder: 20260712,
    timeline: [
      {
        id: 'app-010-submit',
        date: '12/07/2026',
        description: 'Candidate submitted application.',
        label: 'Application received',
      },
    ],
    updatedAt: '12/07/2026',
  },
]

export function computeRecruiterApplicationStats(
  applications: ReadonlyArray<RecruiterApplicationItem>,
): RecruiterApplicationStats {
  const respondedStatuses = new Set<RecruiterApplicationStatus>([
    'screening',
    'interview',
    'offer',
    'hired',
    'rejected',
  ])
  const responded = applications.filter((application) => respondedStatuses.has(application.status)).length
  const responseRate = applications.length > 0 ? Math.round((responded / applications.length) * 100) : 0

  return {
    interview: applications.filter((application) => application.status === 'interview').length,
    new: applications.filter((application) => application.status === 'new').length,
    responseRate: `${responseRate}%`,
    total: applications.length,
  }
}
