import type { AdminSettingsTranslations } from '../../../types'

export const adminSettings: AdminSettingsTranslations = {
  routeLabel: '管理者 — 設定', pageTitle: '管理者設定', pageSubtitle: 'プロフィール、セキュリティ、表示設定を管理します。',
  summary: { accountId: 'アカウントID', email: 'メール', role: '役割', adminRole: '管理者', fallbackName: 'NexHire 管理者', changeAvatar: '写真を変更', saveAvatar: '写真を保存', cancelAvatar: 'キャンセル', removeAvatar: '写真を削除', avatarHint: 'JPG、PNG、WEBP、最大5 MB。', invalidAvatar: '5 MB以下のJPG、PNG、WEBP画像を使用してください。', avatarError: 'プロフィール写真を更新できません。' },
  profile: { title: '個人情報', description: '管理画面でアカウントを識別するための情報です。', fullName: '氏名', fullNamePlaceholder: '氏名を入力', phone: '電話番号', phonePlaceholder: '電話番号を入力', email: 'ログインメール', emailHint: 'メールはここでは変更できません。', role: '役割', save: '変更を保存', saving: '保存中...', reset: '変更を破棄', saveSuccess: 'アカウント情報を更新しました。', saveError: 'アカウント情報を更新できませんでした。', validation: { fullNameRequired: '氏名を入力してください。', fullNameMin: '氏名は2文字以上で入力してください。', fullNameMax: '氏名は255文字以内で入力してください。', phoneInvalid: '有効な電話番号を入力してください。', phoneMax: '電話番号は30文字以内で入力してください。' } },
  password: { title: 'パスワード変更', description: '現在とは異なる強力なパスワードを使用してください。', current: '現在のパスワード', next: '新しいパスワード', confirm: '新しいパスワードを確認', show: 'パスワードを表示', hide: 'パスワードを隠す', submit: 'パスワードを更新', submitting: '更新中...', success: 'パスワードを変更しました。', error: 'パスワードを変更できませんでした。', rulesTitle: '強力なパスワードの条件：', lengthRule: '8～128文字', caseRule: '大文字と小文字', numberRule: '数字を1文字以上', symbolRule: '特殊文字を1文字以上', validation: { currentRequired: '現在のパスワードを入力してください。', nextRequired: '新しいパスワードを入力してください。', confirmRequired: '新しいパスワードを確認してください。', length: 'パスワードは8～128文字で入力してください。', mismatch: 'パスワードが一致しません。', reuse: '新しいパスワードは現在のものと異なる必要があります。' }, apiErrors: { invalidCredentials: '現在のパスワードが正しくありません。', passwordReuse: '現在のパスワードは再利用できません。', credentialMissing: 'このアカウントのパスワード情報が見つかりません。' } },
  preferences: { title: '設定とセッション', description: '表示言語を変更するか、現在の管理者セッションを終了します。', language: '表示言語', languageReset: '元に戻す', languageSave: '言語を保存', languageSaveError: '言語設定を保存できませんでした。', languageSaveSuccess: '表示言語を保存しました。', languageSaving: '保存中...', sessionTitle: 'ログイン中のセッション', sessionDescription: 'この端末から安全にログアウトします。', logout: 'ログアウト' },
  logout: { title: 'ログアウトの確認', description: '管理画面にアクセスするには再度ログインが必要です。', confirm: 'ログアウト', cancel: 'ログインを維持' },
  feedback: { loading: 'アカウント情報を読み込み中', errorTitle: '設定を読み込めません', errorDescription: '管理者アカウント情報を取得できませんでした。', retry: '再試行' },
}
