import type { AdminUser, AdminUserStats } from '../types'

export const adminUsersFixture: ReadonlyArray<AdminUser> = [
  {
    id: 'u-001',
    name: 'Nguyễn Mẫn Hà',
    email: 'manha@nexhire.vn',
    role: 'admin',
    status: 'active',
    createdAt: '2024-11-02',
    lastActiveAt: '2026-07-13',
  },
  {
    id: 'u-002',
    name: 'Trần Văn Khoa',
    email: 'khoa.tran@nexhire.vn',
    role: 'admin',
    status: 'active',
    createdAt: '2024-09-18',
    lastActiveAt: '2026-07-12',
  },
  {
    id: 'u-003',
    name: 'Lê Thị Bích Loan',
    email: 'loan.le@brightworks.co',
    role: 'employer',
    status: 'active',
    createdAt: '2025-02-09',
    lastActiveAt: '2026-07-12',
    company: 'BrightWorks',
  },
  {
    id: 'u-004',
    name: 'Phạm Quốc Bảo',
    email: 'bao.pham@kinetic-labs.io',
    role: 'employer',
    status: 'invited',
    createdAt: '2026-06-30',
    lastActiveAt: '2026-07-01',
    company: 'Kinetic Labs',
  },
  {
    id: 'u-005',
    name: 'Đặng Hồng Phúc',
    email: 'phuc.dang@voltway.vn',
    role: 'employer',
    status: 'locked',
    createdAt: '2025-04-22',
    lastActiveAt: '2026-05-29',
    company: 'Voltway',
  },
  {
    id: 'u-006',
    name: 'Vũ Thị Mai Trinh',
    email: 'trinh.vu@nekko.studio',
    role: 'employer',
    status: 'active',
    createdAt: '2025-08-11',
    lastActiveAt: '2026-07-10',
    company: 'Nekko Studio',
  },
  {
    id: 'u-007',
    name: 'Hoàng Anh Tuấn',
    email: 'tuan.hoang@gmail.com',
    role: 'candidate',
    status: 'active',
    createdAt: '2025-12-01',
    lastActiveAt: '2026-07-13',
  },
  {
    id: 'u-008',
    name: 'Ngô Hà My',
    email: 'myngo94@gmail.com',
    role: 'candidate',
    status: 'active',
    createdAt: '2025-10-14',
    lastActiveAt: '2026-07-12',
  },
  {
    id: 'u-009',
    name: 'Đỗ Gia Khang',
    email: 'khang.do@yahoo.com',
    role: 'candidate',
    status: 'locked',
    createdAt: '2024-12-20',
    lastActiveAt: '2026-04-02',
  },
  {
    id: 'u-010',
    name: 'Lý Thanh Thảo',
    email: 'thao.ly@outlook.com',
    role: 'candidate',
    status: 'active',
    createdAt: '2026-01-08',
    lastActiveAt: '2026-07-11',
  },
  {
    id: 'u-011',
    name: 'Bùi Ngọc Hân',
    email: 'hanbui@gmail.com',
    role: 'candidate',
    status: 'invited',
    createdAt: '2026-07-01',
    lastActiveAt: '2026-07-04',
  },
  {
    id: 'u-012',
    name: 'Trương Minh Đức',
    email: 'duc.truong@nexhire.vn',
    role: 'admin',
    status: 'active',
    createdAt: '2025-03-15',
    lastActiveAt: '2026-07-13',
  },
  {
    id: 'u-013',
    name: 'Phan Khánh Vy',
    email: 'vy.phan@mapleleaf.dev',
    role: 'employer',
    status: 'active',
    createdAt: '2025-07-02',
    lastActiveAt: '2026-07-09',
    company: 'Mapleleaf',
  },
  {
    id: 'u-014',
    name: 'Tô Cẩm Tú',
    email: 'camtu.to@nexhire.vn',
    role: 'admin',
    status: 'locked',
    createdAt: '2024-05-20',
    lastActiveAt: '2025-11-14',
  },
  {
    id: 'u-015',
    name: 'Hà Diệu Linh',
    email: 'linh.ha@gmail.com',
    role: 'candidate',
    status: 'active',
    createdAt: '2026-02-12',
    lastActiveAt: '2026-07-08',
  },
  {
    id: 'u-016',
    name: 'Võ Trọng Nghĩa',
    email: 'nghia.vo@auroratech.vn',
    role: 'employer',
    status: 'active',
    createdAt: '2025-06-04',
    lastActiveAt: '2026-07-12',
    company: 'Aurora Tech',
  },
  {
    id: 'u-017',
    name: 'Châu Bảo Châu',
    email: 'chau.chau@gmail.com',
    role: 'candidate',
    status: 'active',
    createdAt: '2026-03-21',
    lastActiveAt: '2026-07-13',
  },
  {
    id: 'u-018',
    name: 'Lại Hữu Phước',
    email: 'phuoc.lai@oceanix.io',
    role: 'employer',
    status: 'invited',
    createdAt: '2026-06-28',
    lastActiveAt: '2026-06-30',
    company: 'Oceanix',
  },
  {
    id: 'u-019',
    name: 'Đinh Mai Phương',
    email: 'phuong.dinh@nexhire.vn',
    role: 'admin',
    status: 'active',
    createdAt: '2024-10-30',
    lastActiveAt: '2026-07-11',
  },
  {
    id: 'u-020',
    name: 'Kiều Minh Quân',
    email: 'quan.kieu@students.uit.vn',
    role: 'candidate',
    status: 'locked',
    createdAt: '2024-08-19',
    lastActiveAt: '2026-02-18',
  },
]

export function computeAdminStats(users: ReadonlyArray<AdminUser>): AdminUserStats {
  const total = users.length
  let candidates = 0
  let employers = 0
  let locked = 0

  for (const user of users) {
    if (user.role === 'candidate') candidates += 1
    if (user.role === 'employer') employers += 1
    if (user.status === 'locked') locked += 1
  }

  return { total, candidates, employers, locked }
}
